# -*- mode: python -*-

Import("env_link_to_getmemusage")
env = env_link_to_getmemusage

sources = Split("""
    monitor.cpp
    """)

headers = [
    env.File("monitor.h"),
    ]

lib = env.SharedLibrary("monitor", sources)

files = {
    "lib": lib,
    "include": headers
    }

Return("files")
